name:                spar
version:             0.1.0.0
github:              "Richard-zhang/spar"
license:             BSD3
author:              "Shuhao Zhang"
maintainer:          "rzsh2003@gmail.com"
copyright:           "Copyright (c) 2019 Shuhao Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Richard-zhang/spar#readme>

dependencies:
- base >= 4.9 && < 5
- free >= 5.0 && < 5.1
- mtl >= 2.2.1 && < 2.3
- singletons >= 2.4 && < 2.5
- prettyprinter >= 1.2 && < 1.3
- quoted-prettyprinter >= 0.1 && < 0.2
- constrained-control >= 0.1 && < 0.2
- constraints >= 0.10 && < 0.11
- ivector >= 0.1 && < 0.2
- containers == 0.6.0.1
- indexed-free <= 0.4

library:
  source-dirs: src

executables:
  spar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spar

tests:
  spar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spar
