library:
  source-dirs: src
  ghc-options:
  - -Wall
tests:
  spar-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spar
    - hspec >= 2.7 && < 2.8
    - type-spec > 0.3 && <= 0.4
    - should-not-typecheck >= 2.1 && < 2.2
copyright: Copyright (c) 2019 Shuhao Zhang
maintainer: rzsh2003@gmail.com
dependencies:
- bytestring
- time
- cassava >= 0.5 && < 0.6
- statistics >= 0.15 && < 0.16
- Chart >= 1.9 && < 2.0
- Chart-diagrams >= 1.9 && < 2.0
- split == 0.2.3.3
- vector >= 0.12 && < 0.13
- directory
- random
- filepath
- process >= 1.6 && < 1.7
- base >= 4.9 && < 5
- free >= 5.0 && < 5.1
- mtl >= 2.2.1 && < 2.3
- singletons >= 2.4 && < 2.5
- prettyprinter >= 1.2 && < 1.3
- quoted-prettyprinter >= 0.1 && < 0.2
- constrained-control >= 0.1 && < 0.2
- constraints >= 0.10 && < 0.11
- ivector >= 0.1 && < 0.2
- containers >= 0.5 && < 0.6
- indexed <= 0.2
- type-natural >= 0.8 && < 0.9
- language-c >= 0.8 && < 0.9
- mtl >= 2.2 && < 2.3
- deepseq >= 1.4 && < 1.5
name: spar
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Shuhao Zhang
github: Richard-zhang/spar
license: BSD3
executables:
  spar-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spar
description: Please see the README on GitHub at <https://github.com/Richard-zhang/spar#readme>
